// <auto-generated />
using System;
using EndpointSecurity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EndpointSecurity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EndpointSecurityDbContext))]
    [Migration("20260714050755_AddSecurityPostureSnapshots")]
    partial class AddSecurityPostureSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EndpointSecurity.Domain.Entities.ManagedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("ManagedDevices", (string)null);
                });

            modelBuilder.Entity("EndpointSecurity.Domain.Entities.SecurityPostureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AntivirusSignatureAgeDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DefenderEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("FirewallDomainEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("FirewallPrivateEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("FirewallPublicEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("RealTimeProtectionEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("RebootRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CollectedAtUtc");

                    b.ToTable("SecurityPostureSnapshots", (string)null);
                });

            modelBuilder.Entity("EndpointSecurity.Domain.Entities.SecurityPostureSnapshot", b =>
                {
                    b.HasOne("EndpointSecurity.Domain.Entities.ManagedDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
